@hostAddress = http://localhost:5188/api/patients

###

POST {{hostAddress}}/
Content-Type: application/json

{
  "Name": "Anto Guarnieri",
  "Email": "anto@example.com"
}

###

GET {{hostAddress}}/
Accept: application/json

###

GET {{hostAddress}}/?Page=2&RecordsPerPage=2
Accept: application/json

###

GET {{hostAddress}}/?Name=Franco
Accept: application/json

###

GET {{hostAddress}}/?Email=anto@example.com
Accept: application/json

###

GET {{hostAddress}}/?Name=Anto&Email=anto@example.com
Accept: application/json

###

GET {{hostAddress}}/01a02a4c-ca03-7644-afb2-e3de12a57ade

###

PUT {{hostAddress}}/01a02a4c-ca03-7644-afb2-e3de12a57ade
Content-Type: application/json

{
  "Name": "Anto Guarnieri - actualizado",
  "Email": "anto.actualizado@example.com"
}

###

DELETE {{hostAddress}}/01a02a4c-ca03-7644-afb2-e3de12a57ade
Accept: application/json
